-- AlterTable
ALTER TABLE "Article" ADD COLUMN     "assq" INTEGER,
ADD COLUMN     "bts" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "done" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "image_url" TEXT DEFAULT '',
ADD COLUMN     "location" TEXT,
ADD COLUMN     "mpq" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "ms" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "notes" TEXT,
ADD COLUMN     "order_qty" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "palq" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "qty_in_sales" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "top_up" BOOLEAN NOT NULL DEFAULT false;
